services:
  backend:
    build: ./backend
    ports:
      - "5555:5001"
    volumes:
      - ./backend/src:/app/src
    env_file: ./backend/.env
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data
    env_file: .env
